model_checkpoint_last_only:
  _target_: src.utils.model_checkpoint_callback.FullAndWeightsModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_last"
  monitor: null
  verbose: False
  save_last: True
  save_top_k: 1
  mode: "min"
  auto_insert_metric_name: False
  save_weights_only: False
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 1
  save_on_train_epoch_end: True
